// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IPostFields {
  /** Title */
  title: string;

  /** Slug */
  slug: string;

  /** Emoji */
  emoji?: string | undefined;

  /** Publication Date */
  date: string;

  /** Content */
  content?: string | undefined;

  /** Footnote */
  footnote?: string | undefined;
}

/** A blog post. */

export interface IPost extends Entry<IPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'post';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ITalkFields {
  /** Title */
  title: string;

  /** Slug */
  slug?: string | undefined;

  /** Emoji */
  emoji: string;

  /** Presentation Date */
  date?: string | undefined;

  /** Description */
  description?: string | undefined;

  /** SpeakerDeck URL */
  url?: string | undefined;
}

/** A conference talk. */

export interface ITalk extends Entry<ITalkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'talk';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'post' | 'talk';

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
